apiVersion: v1
kind: Pod
metadata:
  name: some-scylla
  namespace: third-project
  labels:
    app: scylla
spec:
  hostname: scylladb
  containers:
    - name: scylla
      image: scylladb/scylla
      args: ["--smp", "1", "-d"]
      ports:
        - containerPort: 9042
