apiVersion: v1
kind: Service
metadata:
  name: scylla-service
  namespace: third-project
spec:
  selector:
    app: scylla
  ports:
    - protocol: TCP
      port: 9042
      targetPort: 9042
  type: ClusterIP

