apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-mongos
  namespace: third-project
spec:
  replicas: 2
  selector:
    matchLabels:
      role: mongo-mongos
  template:
    metadata:
      labels:
        role: mongo-mongos
    spec:
      containers:
      - name: mongos
        image: mongo:latest
        command: ["mongos", "--configdb", "configReplSet/mongo-config-0.mongo-config,mongo-config-1.mongo-config,mongo-config-2.mongo-config:27017", "--bind_ip_all"]
        ports:
        - containerPort: 27017
