apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-shard1
  namespace: third-project
spec:
  serviceName: mongo-shard1
  replicas: 3
  selector:
    matchLabels:
      role: mongo-shard1
  template:
    metadata:
      labels:
        role: mongo-shard1
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        command: ["mongod", "--shardsvr", "--replSet", "shard1ReplSet", "--bind_ip_all"]
        ports:
        - containerPort: 27017
