apiVersion: v1
kind: Pod
metadata:
  name: minio
  namespace: third-project
  labels:
    app: minio
spec:
  containers:
    - name: minio
      image: minio/minio
      args: ["server", "/home/genetic152/minio"]
      ports:
        - containerPort: 9000
      volumeMounts:
        - name: minio-storage
          mountPath: "/home/genetic152/minio"
  volumes:
    - name: minio-storage
      emptyDir: {}
