apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: third-project
data:
  redis.conf: |
    bind 0.0.0.0
    protected-mode yes
    port 6379
    cluster-enabled yes
    cluster-node-timeout 5000
    appendonly yes
