apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster
  namespace: third-project
spec:
  serviceName: redis
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-config
          mountPath: /usr/local/etc/redis
          subPath: redis.conf
        args:
          - "--port"
          - "6379"
          - "--cluster-enabled"
          - "yes"
          - "--cluster-node-timeout"
          - "5000"
      volumes:
      - name: redis-config
        configMap:
          name: redis-config

